version: '3.8'

services:
  postgres-jira:
    image: postgres:latest
    container_name: postgres-jira
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
      POSTGRES_DB: jira
    ports:
      - "5434:5432"
    volumes:
      - postgresVolume:/var/lib/postgresql/data

  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    environment:
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_DB_TYPE: postgres72
      ATL_JDBC_URL: jdbc:postgresql://postgres-jira:5432/jira
      ATL_JDBC_USER: jira
      ATL_JDBC_PASSWORD: jira
    ports:
      - "5000:8080"
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    depends_on:
      - postgres-jira

volumes:
  postgresVolume:
  jiraVolume:
